version: "3.8"
services:
  postgre__url-shortener:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
#    volumes:
#      - /var/postgre__url-shortener:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  redis_url-shortener:
    image: redis:6.2-alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass secret
    ports:
      - "6379:6379"
    restart: always

  go-container:
    image: autokz/golang-testing:1.17-alpine
    working_dir: /app
    environment:
      SERVER_PORT: 60250
      SERVER_HOST: localhost
      METRIC_SERVER_ADDRESS: 1
      METRIC_SERVER_PORT: 1
      METRIC_APP_NAME: test
      METRIC_TIMEOUT: 200
      POSTGRES_HOST: postgre__url-shortener
      POSTGRES_PORT: 5432
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
      REDIS_PORT: 6379
      REDIS_HOST: redis_url-shortener
      REDIS_PASSWORD: secret
      REDIS_DB: 0
    volumes:
      - "../:/app/project"
      - "/go:/go"
    depends_on:
      - postgre__url-shortener
      - redis_url-shortener

    command: go run main.go